package MapGen_Language.sandbox;

/*Generated by MPS */

import JavaRuntime.Runtime.MyMap;
import JavaRuntime.Runtime.Player;

public class map_Map {
  public static MyMap myMap = new MyMap();

  private int height = 0;
  private int width = 0;
  private int neighbours = 0;

  public void init() {
    {
      Player player = new Player("Player1", 1500);
      myMap.addPlayer(player);
    }

  }
}
