package MapGen_Language.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int ColorReference = 0;
  public static final int Colorable = 1;
  public static final int Effect = 2;
  public static final int Equipment = 3;
  public static final int Field = 4;
  public static final int Fight = 5;
  public static final int Frequent = 6;
  public static final int Map = 7;
  public static final int Moderate = 8;
  public static final int MovementModifier = 9;
  public static final int Object = 10;
  public static final int Occurrence = 11;
  public static final int Player = 12;
  public static final int Rare = 13;
  public static final int Rules = 14;
  public static final int Target = 15;
  public static final int TargetField = 16;
  public static final int TargetObject = 17;
  public static final int Unreachable = 18;
  public static final int Without = 19;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x6603edcde014f88L, 0xa0d068aced597e99L);
    builder.put(0x29e1c30f20e16300L, ColorReference);
    builder.put(0x29e1c30f20e162ffL, Colorable);
    builder.put(0x20ce2a992dbb69dfL, Effect);
    builder.put(0x4368f4c8e6e9f0c5L, Equipment);
    builder.put(0x29e1c30f20e16305L, Field);
    builder.put(0x20ce2a992dc56b05L, Fight);
    builder.put(0x20ce2a992dc81eb7L, Frequent);
    builder.put(0x29e1c30f20e1630aL, Map);
    builder.put(0x20ce2a992dc81eb8L, Moderate);
    builder.put(0x29e1c30f20ed7740L, MovementModifier);
    builder.put(0x29e1c30f20e1630dL, Object);
    builder.put(0x20ce2a992dc81eb9L, Occurrence);
    builder.put(0x29e1c30f20e16310L, Player);
    builder.put(0x20ce2a992dc81eb6L, Rare);
    builder.put(0x29e1c30f20ed7731L, Rules);
    builder.put(0x20ce2a992dbb69d8L, Target);
    builder.put(0x20ce2a992dbb69d9L, TargetField);
    builder.put(0x20ce2a992dbb69dcL, TargetObject);
    builder.put(0x20ce2a992dbb69acL, Unreachable);
    builder.put(0x20ce2a992dbb69afL, Without);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
