package MapGen_Language.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptColorReference = createDescriptorForColorReference();
  /*package*/ final ConceptDescriptor myConceptColorable = createDescriptorForColorable();
  /*package*/ final ConceptDescriptor myConceptEffect = createDescriptorForEffect();
  /*package*/ final ConceptDescriptor myConceptEquipment = createDescriptorForEquipment();
  /*package*/ final ConceptDescriptor myConceptField = createDescriptorForField();
  /*package*/ final ConceptDescriptor myConceptFight = createDescriptorForFight();
  /*package*/ final ConceptDescriptor myConceptFrequent = createDescriptorForFrequent();
  /*package*/ final ConceptDescriptor myConceptMap = createDescriptorForMap();
  /*package*/ final ConceptDescriptor myConceptModerate = createDescriptorForModerate();
  /*package*/ final ConceptDescriptor myConceptMovementModifier = createDescriptorForMovementModifier();
  /*package*/ final ConceptDescriptor myConceptObject = createDescriptorForObject();
  /*package*/ final ConceptDescriptor myConceptOccurrence = createDescriptorForOccurrence();
  /*package*/ final ConceptDescriptor myConceptPlayer = createDescriptorForPlayer();
  /*package*/ final ConceptDescriptor myConceptRare = createDescriptorForRare();
  /*package*/ final ConceptDescriptor myConceptRules = createDescriptorForRules();
  /*package*/ final ConceptDescriptor myConceptTarget = createDescriptorForTarget();
  /*package*/ final ConceptDescriptor myConceptTargetField = createDescriptorForTargetField();
  /*package*/ final ConceptDescriptor myConceptTargetObject = createDescriptorForTargetObject();
  /*package*/ final ConceptDescriptor myConceptUnreachable = createDescriptorForUnreachable();
  /*package*/ final ConceptDescriptor myConceptWithout = createDescriptorForWithout();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptColorReference, myConceptColorable, myConceptEffect, myConceptEquipment, myConceptField, myConceptFight, myConceptFrequent, myConceptMap, myConceptModerate, myConceptMovementModifier, myConceptObject, myConceptOccurrence, myConceptPlayer, myConceptRare, myConceptRules, myConceptTarget, myConceptTargetField, myConceptTargetObject, myConceptUnreachable, myConceptWithout);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.ColorReference:
        return myConceptColorReference;
      case LanguageConceptSwitch.Colorable:
        return myConceptColorable;
      case LanguageConceptSwitch.Effect:
        return myConceptEffect;
      case LanguageConceptSwitch.Equipment:
        return myConceptEquipment;
      case LanguageConceptSwitch.Field:
        return myConceptField;
      case LanguageConceptSwitch.Fight:
        return myConceptFight;
      case LanguageConceptSwitch.Frequent:
        return myConceptFrequent;
      case LanguageConceptSwitch.Map:
        return myConceptMap;
      case LanguageConceptSwitch.Moderate:
        return myConceptModerate;
      case LanguageConceptSwitch.MovementModifier:
        return myConceptMovementModifier;
      case LanguageConceptSwitch.Object:
        return myConceptObject;
      case LanguageConceptSwitch.Occurrence:
        return myConceptOccurrence;
      case LanguageConceptSwitch.Player:
        return myConceptPlayer;
      case LanguageConceptSwitch.Rare:
        return myConceptRare;
      case LanguageConceptSwitch.Rules:
        return myConceptRules;
      case LanguageConceptSwitch.Target:
        return myConceptTarget;
      case LanguageConceptSwitch.TargetField:
        return myConceptTargetField;
      case LanguageConceptSwitch.TargetObject:
        return myConceptTargetObject;
      case LanguageConceptSwitch.Unreachable:
        return myConceptUnreachable;
      case LanguageConceptSwitch.Without:
        return myConceptWithout;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForColorReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MapGen_Language", "ColorReference", 0x6603edcde014f88L, 0xa0d068aced597e99L, 0x29e1c30f20e16300L);
    b.class_(false, false, false);
    b.origin("r:58a5e344-c0be-49ce-83fe-40662317bfd1(MapGen_Language.structure)/3017907695058510592");
    b.version(3);
    b.associate("color", 0x29e1c30f20e16301L).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93c84351fL).optional(false).origin("3017907695058510593").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColorable() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MapGen_Language", "Colorable", 0x6603edcde014f88L, 0xa0d068aced597e99L, 0x29e1c30f20e162ffL);
    b.class_(false, false, false);
    b.origin("r:58a5e344-c0be-49ce-83fe-40662317bfd1(MapGen_Language.structure)/3017907695058510591");
    b.version(3);
    b.aggregate("color", 0x29e1c30f20e16303L).target(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x29e1c30f20e16300L).optional(false).ordered(true).multiple(false).origin("3017907695058510595").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEffect() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MapGen_Language", "Effect", 0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dbb69dfL);
    b.class_(false, true, false);
    b.origin("r:58a5e344-c0be-49ce-83fe-40662317bfd1(MapGen_Language.structure)/2363873691801709023");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEquipment() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MapGen_Language", "Equipment", 0x6603edcde014f88L, 0xa0d068aced597e99L, 0x4368f4c8e6e9f0c5L);
    b.class_(false, false, false);
    // extends: MapGen_Language.structure.Effect
    b.super_(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dbb69dfL);
    b.origin("r:58a5e344-c0be-49ce-83fe-40662317bfd1(MapGen_Language.structure)/4857401341823807685");
    b.version(3);
    b.aggregate("movementModifier", 0x4368f4c8e6e9f0c6L).target(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x29e1c30f20ed7740L).optional(true).ordered(true).multiple(false).origin("4857401341823807686").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MapGen_Language", "Field", 0x6603edcde014f88L, 0xa0d068aced597e99L, 0x29e1c30f20e16305L);
    b.class_(false, false, false);
    // extends: MapGen_Language.structure.Colorable
    b.super_(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x29e1c30f20e162ffL);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:58a5e344-c0be-49ce-83fe-40662317bfd1(MapGen_Language.structure)/3017907695058510597");
    b.version(3);
    b.property("movement", 0x29e1c30f20e16308L).type(PrimitiveTypeId.INTEGER).origin("3017907695058510600").done();
    b.aggregate("occurrence", 0x20ce2a992dc81ebaL).target(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dc81eb9L).optional(false).ordered(true).multiple(false).origin("2363873691802541754").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFight() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MapGen_Language", "Fight", 0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dc56b05L);
    b.class_(false, false, false);
    // extends: MapGen_Language.structure.Effect
    b.super_(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dbb69dfL);
    b.origin("r:58a5e344-c0be-49ce-83fe-40662317bfd1(MapGen_Language.structure)/2363873691802364677");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFrequent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MapGen_Language", "Frequent", 0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dc81eb7L);
    b.class_(false, false, false);
    // extends: MapGen_Language.structure.Occurrence
    b.super_(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dc81eb9L);
    b.origin("r:58a5e344-c0be-49ce-83fe-40662317bfd1(MapGen_Language.structure)/2363873691802541751");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMap() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MapGen_Language", "Map", 0x6603edcde014f88L, 0xa0d068aced597e99L, 0x29e1c30f20e1630aL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:58a5e344-c0be-49ce-83fe-40662317bfd1(MapGen_Language.structure)/3017907695058510602");
    b.version(3);
    b.property("Height", 0x29e1c30f20e2a701L).type(PrimitiveTypeId.INTEGER).origin("3017907695058593537").done();
    b.property("Width", 0x29e1c30f20e2a703L).type(PrimitiveTypeId.INTEGER).origin("3017907695058593539").done();
    b.property("Neighbours", 0x20ce2a992db9470eL).type(PrimitiveTypeId.INTEGER).origin("2363873691801569038").done();
    b.aggregate("players", 0x29e1c30f20e2a706L).target(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x29e1c30f20e16310L).optional(true).ordered(true).multiple(true).origin("3017907695058593542").done();
    b.aggregate("fields", 0x29e1c30f20e2a708L).target(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x29e1c30f20e16305L).optional(true).ordered(true).multiple(true).origin("3017907695058593544").done();
    b.aggregate("objects", 0x29e1c30f20e2a70bL).target(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x29e1c30f20e1630dL).optional(true).ordered(true).multiple(true).origin("3017907695058593547").done();
    b.aggregate("rules", 0x29e1c30f20ed773bL).target(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x29e1c30f20ed7731L).optional(true).ordered(true).multiple(true).origin("3017907695059302203").done();
    b.alias("map");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForModerate() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MapGen_Language", "Moderate", 0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dc81eb8L);
    b.class_(false, false, false);
    // extends: MapGen_Language.structure.Occurrence
    b.super_(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dc81eb9L);
    b.origin("r:58a5e344-c0be-49ce-83fe-40662317bfd1(MapGen_Language.structure)/2363873691802541752");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMovementModifier() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MapGen_Language", "MovementModifier", 0x6603edcde014f88L, 0xa0d068aced597e99L, 0x29e1c30f20ed7740L);
    b.class_(false, false, false);
    b.origin("r:58a5e344-c0be-49ce-83fe-40662317bfd1(MapGen_Language.structure)/3017907695059302208");
    b.version(3);
    b.property("modifier", 0x29e1c30f20ed7741L).type(PrimitiveTypeId.INTEGER).origin("3017907695059302209").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForObject() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MapGen_Language", "Object", 0x6603edcde014f88L, 0xa0d068aced597e99L, 0x29e1c30f20e1630dL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:58a5e344-c0be-49ce-83fe-40662317bfd1(MapGen_Language.structure)/3017907695058510605");
    b.version(3);
    b.property("character", 0x44195949d3fcc792L).type(MetaIdFactory.dataTypeId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x1177d450137L)).origin("4907051442620909458").done();
    b.property("number", 0x20ce2a992dc73192L).type(PrimitiveTypeId.INTEGER).origin("2363873691802481042").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOccurrence() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MapGen_Language", "Occurrence", 0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dc81eb9L);
    b.class_(false, true, false);
    b.origin("r:58a5e344-c0be-49ce-83fe-40662317bfd1(MapGen_Language.structure)/2363873691802541753");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPlayer() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MapGen_Language", "Player", 0x6603edcde014f88L, 0xa0d068aced597e99L, 0x29e1c30f20e16310L);
    b.class_(false, false, false);
    // extends: MapGen_Language.structure.Colorable
    b.super_(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x29e1c30f20e162ffL);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:58a5e344-c0be-49ce-83fe-40662317bfd1(MapGen_Language.structure)/3017907695058510608");
    b.version(3);
    b.property("movement", 0x20ce2a992dc9fbcaL).type(PrimitiveTypeId.INTEGER).origin("2363873691802663882").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRare() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MapGen_Language", "Rare", 0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dc81eb6L);
    b.class_(false, false, false);
    // extends: MapGen_Language.structure.Occurrence
    b.super_(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dc81eb9L);
    b.origin("r:58a5e344-c0be-49ce-83fe-40662317bfd1(MapGen_Language.structure)/2363873691802541750");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRules() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MapGen_Language", "Rules", 0x6603edcde014f88L, 0xa0d068aced597e99L, 0x29e1c30f20ed7731L);
    b.class_(false, false, false);
    b.origin("r:58a5e344-c0be-49ce-83fe-40662317bfd1(MapGen_Language.structure)/3017907695059302193");
    b.version(3);
    b.aggregate("target", 0x20ce2a992dbb69e1L).target(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dbb69d8L).optional(false).ordered(true).multiple(false).origin("2363873691801709025").done();
    b.aggregate("effect", 0x20ce2a992dbb69e3L).target(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dbb69dfL).optional(false).ordered(true).multiple(false).origin("2363873691801709027").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTarget() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MapGen_Language", "Target", 0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dbb69d8L);
    b.class_(false, true, false);
    b.origin("r:58a5e344-c0be-49ce-83fe-40662317bfd1(MapGen_Language.structure)/2363873691801709016");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTargetField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MapGen_Language", "TargetField", 0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dbb69d9L);
    b.class_(false, false, false);
    // extends: MapGen_Language.structure.Target
    b.super_(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dbb69d8L);
    b.origin("r:58a5e344-c0be-49ce-83fe-40662317bfd1(MapGen_Language.structure)/2363873691801709017");
    b.version(3);
    b.associate("field", 0x20ce2a992dbb69daL).target(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x29e1c30f20e16305L).optional(false).origin("2363873691801709018").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTargetObject() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MapGen_Language", "TargetObject", 0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dbb69dcL);
    b.class_(false, false, false);
    // extends: MapGen_Language.structure.Target
    b.super_(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dbb69d8L);
    b.origin("r:58a5e344-c0be-49ce-83fe-40662317bfd1(MapGen_Language.structure)/2363873691801709020");
    b.version(3);
    b.associate("object", 0x20ce2a992dbb69ddL).target(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x29e1c30f20e1630dL).optional(false).origin("2363873691801709021").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUnreachable() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MapGen_Language", "Unreachable", 0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dbb69acL);
    b.class_(false, false, false);
    // extends: MapGen_Language.structure.Effect
    b.super_(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dbb69dfL);
    b.origin("r:58a5e344-c0be-49ce-83fe-40662317bfd1(MapGen_Language.structure)/2363873691801708972");
    b.version(3);
    b.aggregate("without", 0x20ce2a992dbb69e6L).target(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dbb69afL).optional(true).ordered(true).multiple(false).origin("2363873691801709030").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWithout() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MapGen_Language", "Without", 0x6603edcde014f88L, 0xa0d068aced597e99L, 0x20ce2a992dbb69afL);
    b.class_(false, false, false);
    b.origin("r:58a5e344-c0be-49ce-83fe-40662317bfd1(MapGen_Language.structure)/2363873691801708975");
    b.version(3);
    b.associate("object", 0x20ce2a992dbb69b0L).target(0x6603edcde014f88L, 0xa0d068aced597e99L, 0x29e1c30f20e1630dL).optional(false).origin("2363873691801708976").done();
    return b.create();
  }
}
