package JavaRuntime.Runtime;

/*Generated by MPS */


public class MapObject {
  /*package*/ String name;
  /*package*/ char character;
  /*package*/ int number;

  public MapObject(String name, char c, int number) {
    this.name = name;
    this.character = c;
    this.number = number;
  }

  public MapObject() {
  }
}
