package JavaRuntime.Runtime;

/*Generated by MPS */


public class Player {
  /*package*/ String name;
  /*package*/ int movement;


  public Player() {
  }
  public Player(String name, int movement) {
  }
}
